version: "3.8"

services:
  # ---------- Auth Service ----------
  auth:
    build:
      context: .
      dockerfile: ./cmd/auth-service/Dockerfile
    container_name: auth_service
    # Пробрасываем порт 8080 наружу
    environment:
      - DB_CONN_STR=postgres://postgres:postgres@postgres:5432/postgres_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis:6379
      - AUTH_SERVICE_PORT=8001
      - JWT_SECRET=${JWT_SECRET:-secret_key}
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - rabbitmq
      - redis

  # ---------- Config Service ----------
  config:
    build:
      context: .
      dockerfile: ./cmd/config-service/Dockerfile
    container_name: config_service
    environment:
      - DB_CONN_STR=postgres://postgres:postgres@postgres:5432/postgres_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis:6379
      - CONFIG_SERVICE_PORT=8002
      - JWT_SECRET=${JWT_SECRET:-secret_key}
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - rabbitmq
      - redis

  # ---------- Aggregator Service ----------
  aggregator:
    build:
      context: .
      dockerfile: ./cmd/aggregator-service/Dockerfile
    container_name: aggregator_service
    volumes:
      - ./data/pricelists:/data
    environment:
      - DB_CONN_STR=postgres://postgres:postgres@postgres:5432/postgres_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis:6379
      - AGG_SERVICE_PORT=8003
    ports:
      - "8003:8003"
    depends_on:
      - postgres
      - rabbitmq
      - redis

  importer:
    build:
      context: .
      dockerfile: cmd/importer/Dockerfile
    container_name: importer_service
    volumes:
      - ./data/pricelists:/data
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq

  # ---------- Notifications Service ----------
  notifications:
    build:
      context: .
      dockerfile: ./cmd/notifications-service/Dockerfile
    container_name: notifications_service
    environment:
      - DB_CONN_STR=postgres://postgres:postgres@postgres:5432/postgres_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis:6379
      - NOTIFICATIONS_PORT=8004
      - JWT_SECRET=${JWT_SECRET:-secret_key}
    ports:
      - "8004:8004"
    depends_on:
      - postgres
      - rabbitmq
      - redis

  # ---------- Gateway (API Gateway) ----------
  gateway:
    build:
      context: .
      dockerfile: ./cmd/gateway/Dockerfile
    container_name: gateway_service
    environment:
      - AUTH_SERVICE_URL=http://auth:8001
      - CONFIG_SERVICE_URL=http://config:8002
      - AGGREGATOR_SERVICE_URL=http://aggregator:8003
      - NOTIFICATIONS_SERVICE_URL=http://notifications:8004
      - JWT_SECRET=${JWT_SECRET:-secret_key}
      # ... возможно, здесь же RABBITMQ_URL, REDIS_URL, etc
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - config
      - aggregator
      - notifications

  # ---------- RabbitMQ ----------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # веб-интерфейс
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # ---------- Postgres ----------
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  # ---------- Redis ----------
  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
